import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { FileText, ShieldAlert, Printer, CheckCircle2, Download, ExternalLink, ShieldCheck } from 'lucide-react';
import { EULA_TEXT_CONTENT, getEulaAcceptance, saveEulaAcceptance } from '../../utils/license';

export const EulaModal: React.FC = () => {
  const { closeModal, showToast, user } = useApp();
  const eulaState = getEulaAcceptance();
  const [accepted, setAccepted] = useState(eulaState.accepted);

  const handleAccept = () => {
    saveEulaAcceptance(user?.name || 'Administrator');
    setAccepted(true);
    showToast('✓ End User License Agreement (EULA) signed & accepted.');
    closeModal();
  };

  const handlePrint = () => {
    const printContent = `
      <html>
        <head>
          <title>${EULA_TEXT_CONTENT.title}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; }
            h1 { font-size: 20px; text-transform: uppercase; margin-bottom: 5px; color: #0f172a; }
            h2 { font-size: 14px; color: #475569; margin-bottom: 20px; }
            .section { margin-bottom: 24px; }
            .heading { font-weight: bold; font-size: 14px; margin-bottom: 8px; color: #0f172a; text-transform: uppercase; }
            .body { font-size: 12px; white-space: pre-wrap; color: #334155; }
            .footer { margin-top: 40px; border-top: 2px solid #cbd5e1; padding-top: 20px; font-size: 11px; text-align: center; }
          </style>
        </head>
        <body>
          <h1>${EULA_TEXT_CONTENT.title}</h1>
          <h2>${EULA_TEXT_CONTENT.subtitle} — ${EULA_TEXT_CONTENT.version}</h2>
          <hr/>
          ${EULA_TEXT_CONTENT.sections.map(s => `
            <div className="section">
              <div className="heading">${s.heading}</div>
              <div className="body">${s.body}</div>
            </div>
          `).join('')}
          <div className="footer">
            Officially generated by SIRTOY LENDING PLUS SOFTWARE • Developer Support: https://www.facebook.com/profile.php?id=61595333360264
          </div>
        </body>
      </html>
    `;
    const win = window.open('', '_blank');
    if (win) {
      win.document.write(printContent);
      win.document.close();
      win.focus();
      win.print();
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md overflow-y-auto">
      <div className="card w-full max-w-3xl bg-white rounded-3xl shadow-2xl border border-slate-200 overflow-hidden my-auto animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="p-6 bg-slate-900 text-white border-b-4 border-amber-500">
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-center gap-3.5">
              <div className="p-3.5 rounded-2xl bg-amber-500/20 text-amber-400 border border-amber-500/40">
                <FileText className="w-8 h-8" />
              </div>
              <div>
                <span className="text-[10px] font-black uppercase tracking-widest text-amber-400 block">
                  Legal Contract & Liability Disclaimer
                </span>
                <h2 className="text-lg font-black text-white leading-tight">
                  End User License Agreement (EULA)
                </h2>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handlePrint}
                className="px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-slate-200 font-bold text-xs flex items-center gap-1.5 transition-colors cursor-pointer"
                title="Print or Save EULA as PDF"
              >
                <Printer className="w-4 h-4" />
                <span>Print / PDF</span>
              </button>
              <button
                onClick={closeModal}
                className="px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-slate-300 font-bold text-xs transition-colors cursor-pointer"
              >
                ✕ Isara
              </button>
            </div>
          </div>
        </div>

        {/* EULA Body */}
        <div className="p-6 space-y-5 max-h-[65vh] overflow-y-auto text-slate-800 text-xs leading-relaxed divide-y divide-slate-100">
          <div className="p-4 rounded-2xl bg-amber-50 border border-amber-200 text-amber-950 font-medium text-xs leading-relaxed flex items-start gap-3">
            <ShieldAlert className="w-5 h-5 text-amber-600 flex-none mt-0.5" />
            <div>
              <b>PANAWAGAN SA GUMAGAMIT / KUMPANYA:</b> Ang software na ito ay nakadisensyo bilang tool sa pag-compute at pag-manage ng pautang. Ang kumpanya o user ang may pananagutan sa pagrepaso ng tamang interes, multa, koleksyon, at pagtatago ng backups ng inyong database.
            </div>
          </div>

          {EULA_TEXT_CONTENT.sections.map((sec, idx) => (
            <div key={idx} className="pt-4 first:pt-0 space-y-1.5">
              <h3 className="font-extrabold text-sm text-slate-900 uppercase tracking-wide">
                {sec.heading}
              </h3>
              <p className="whitespace-pre-wrap text-slate-600 font-normal leading-relaxed text-xs">
                {sec.body}
              </p>
            </div>
          ))}
        </div>

        {/* Footer Actions */}
        <div className="p-5 bg-slate-50 border-t border-slate-200 flex flex-wrap items-center justify-between gap-3">
          <div className="text-[11px] text-slate-500 font-semibold flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4 text-emerald-600" />
            <span>Version: {EULA_TEXT_CONTENT.version}</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleAccept}
              className="px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-black text-xs shadow-md transition-all cursor-pointer flex items-center gap-2"
            >
              <CheckCircle2 className="w-4 h-4" />
              <span>{accepted ? '✓ Na-sign na ang EULA' : 'Sumasang-ayon Ako sa EULA'}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
